language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - yarn lint
  - yarn tsc
  - yarn test
  - yarn check-types
  - yarn build:docs
before_install: yarn global add greenkeeper-lockfile@2
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
  - yarn lerna-semantic-release pre
  - yarn lerna-semantic-release perform
  - yarn lerna-semantic-release post
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: './docs'
  project_name: '@action-land'
  github_token: $GH_TOKEN
  on:
    branch: master
